# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/andreas/.local/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/andreas/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andreas/projects/p9-projekt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andreas/projects/p9-projekt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/andreas/.local/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/andreas/.local/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/projects/p9-projekt/CMakeFiles /home/andreas/projects/p9-projekt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/projects/p9-projekt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named output

# Build rule for target.
output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 output
.PHONY : output

# fast build rule for target.
output/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/build
.PHONY : output/fast

src/ChangesList.o: src/ChangesList.cpp.o
.PHONY : src/ChangesList.o

# target to build an object file
src/ChangesList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/ChangesList.cpp.o
.PHONY : src/ChangesList.cpp.o

src/ChangesList.i: src/ChangesList.cpp.i
.PHONY : src/ChangesList.i

# target to preprocess a source file
src/ChangesList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/ChangesList.cpp.i
.PHONY : src/ChangesList.cpp.i

src/ChangesList.s: src/ChangesList.cpp.s
.PHONY : src/ChangesList.s

# target to generate assembly for a file
src/ChangesList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/ChangesList.cpp.s
.PHONY : src/ChangesList.cpp.s

src/aggregation.o: src/aggregation.cpp.o
.PHONY : src/aggregation.o

# target to build an object file
src/aggregation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/aggregation.cpp.o
.PHONY : src/aggregation.cpp.o

src/aggregation.i: src/aggregation.cpp.i
.PHONY : src/aggregation.i

# target to preprocess a source file
src/aggregation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/aggregation.cpp.i
.PHONY : src/aggregation.cpp.i

src/aggregation.s: src/aggregation.cpp.s
.PHONY : src/aggregation.s

# target to generate assembly for a file
src/aggregation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/aggregation.cpp.s
.PHONY : src/aggregation.cpp.s

src/economic.o: src/economic.cpp.o
.PHONY : src/economic.o

# target to build an object file
src/economic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/economic.cpp.o
.PHONY : src/economic.cpp.o

src/economic.i: src/economic.cpp.i
.PHONY : src/economic.i

# target to preprocess a source file
src/economic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/economic.cpp.i
.PHONY : src/economic.cpp.i

src/economic.s: src/economic.cpp.s
.PHONY : src/economic.s

# target to generate assembly for a file
src/economic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/economic.cpp.s
.PHONY : src/economic.cpp.s

src/evaluation.o: src/evaluation.cpp.o
.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/evaluation.cpp.o
.PHONY : src/evaluation.cpp.o

src/evaluation.i: src/evaluation.cpp.i
.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/evaluation.cpp.i
.PHONY : src/evaluation.cpp.i

src/evaluation.s: src/evaluation.cpp.s
.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/evaluation.cpp.s
.PHONY : src/evaluation.cpp.s

src/flexoffer.o: src/flexoffer.cpp.o
.PHONY : src/flexoffer.o

# target to build an object file
src/flexoffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/flexoffer.cpp.o
.PHONY : src/flexoffer.cpp.o

src/flexoffer.i: src/flexoffer.cpp.i
.PHONY : src/flexoffer.i

# target to preprocess a source file
src/flexoffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/flexoffer.cpp.i
.PHONY : src/flexoffer.cpp.i

src/flexoffer.s: src/flexoffer.cpp.s
.PHONY : src/flexoffer.s

# target to generate assembly for a file
src/flexoffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/flexoffer.cpp.s
.PHONY : src/flexoffer.cpp.s

src/generator.o: src/generator.cpp.o
.PHONY : src/generator.o

# target to build an object file
src/generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/generator.cpp.o
.PHONY : src/generator.cpp.o

src/generator.i: src/generator.cpp.i
.PHONY : src/generator.i

# target to preprocess a source file
src/generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/generator.cpp.i
.PHONY : src/generator.cpp.i

src/generator.s: src/generator.cpp.s
.PHONY : src/generator.s

# target to generate assembly for a file
src/generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/generator.cpp.s
.PHONY : src/generator.cpp.s

src/group.o: src/group.cpp.o
.PHONY : src/group.o

# target to build an object file
src/group.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/group.cpp.o
.PHONY : src/group.cpp.o

src/group.i: src/group.cpp.i
.PHONY : src/group.i

# target to preprocess a source file
src/group.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/group.cpp.i
.PHONY : src/group.cpp.i

src/group.s: src/group.cpp.s
.PHONY : src/group.s

# target to generate assembly for a file
src/group.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/group.cpp.s
.PHONY : src/group.cpp.s

src/helperfunctions.o: src/helperfunctions.cpp.o
.PHONY : src/helperfunctions.o

# target to build an object file
src/helperfunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/helperfunctions.cpp.o
.PHONY : src/helperfunctions.cpp.o

src/helperfunctions.i: src/helperfunctions.cpp.i
.PHONY : src/helperfunctions.i

# target to preprocess a source file
src/helperfunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/helperfunctions.cpp.i
.PHONY : src/helperfunctions.cpp.i

src/helperfunctions.s: src/helperfunctions.cpp.s
.PHONY : src/helperfunctions.s

# target to generate assembly for a file
src/helperfunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/helperfunctions.cpp.s
.PHONY : src/helperfunctions.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scheduled_flexoffer.o: src/scheduled_flexoffer.cpp.o
.PHONY : src/scheduled_flexoffer.o

# target to build an object file
src/scheduled_flexoffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/scheduled_flexoffer.cpp.o
.PHONY : src/scheduled_flexoffer.cpp.o

src/scheduled_flexoffer.i: src/scheduled_flexoffer.cpp.i
.PHONY : src/scheduled_flexoffer.i

# target to preprocess a source file
src/scheduled_flexoffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/scheduled_flexoffer.cpp.i
.PHONY : src/scheduled_flexoffer.cpp.i

src/scheduled_flexoffer.s: src/scheduled_flexoffer.cpp.s
.PHONY : src/scheduled_flexoffer.s

# target to generate assembly for a file
src/scheduled_flexoffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/scheduled_flexoffer.cpp.s
.PHONY : src/scheduled_flexoffer.cpp.s

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/tec.o: src/tec.cpp.o
.PHONY : src/tec.o

# target to build an object file
src/tec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/tec.cpp.o
.PHONY : src/tec.cpp.o

src/tec.i: src/tec.cpp.i
.PHONY : src/tec.i

# target to preprocess a source file
src/tec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/tec.cpp.i
.PHONY : src/tec.cpp.i

src/tec.s: src/tec.cpp.s
.PHONY : src/tec.s

# target to generate assembly for a file
src/tec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/tec.cpp.s
.PHONY : src/tec.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... output"
	@echo "... src/ChangesList.o"
	@echo "... src/ChangesList.i"
	@echo "... src/ChangesList.s"
	@echo "... src/aggregation.o"
	@echo "... src/aggregation.i"
	@echo "... src/aggregation.s"
	@echo "... src/economic.o"
	@echo "... src/economic.i"
	@echo "... src/economic.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/flexoffer.o"
	@echo "... src/flexoffer.i"
	@echo "... src/flexoffer.s"
	@echo "... src/generator.o"
	@echo "... src/generator.i"
	@echo "... src/generator.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/helperfunctions.o"
	@echo "... src/helperfunctions.i"
	@echo "... src/helperfunctions.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scheduled_flexoffer.o"
	@echo "... src/scheduled_flexoffer.i"
	@echo "... src/scheduled_flexoffer.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/tec.o"
	@echo "... src/tec.i"
	@echo "... src/tec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

